# Basics
language: c
matrix:
  include:
  - os: osx
    env: TRAVIS_OS_PLATFORM=darwin
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1 TRAVIS_OS_PLATFORM=linux
    compiler: clang
osx_image: xcode8.3
sudo: required
dist: trusty

# Cache
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

# Add ons
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils

# Before install steps
before_install:
  - |
    mkdir -p /tmp/git-lfs
    curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$TRAVIS_OS_PLATFORM-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    /tmp/git-lfs/git-lfs pull
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils;
    fi

# Install steps
install:
  #- export DISPLAY=':99.0'
  #- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe
  - yarn

# Test and build
script:

  # Tests
  # Code linting and standards
  - yarn run lint

  # Unit tests
  - xvfb-maybe yarn run unit

  # End to end test
  - xvfb-maybe yarn run e2e

  # Build
  - yarn run build
