# Basics
image: Visual Studio 2017
platform:
  - x64

# Cache
cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

# Init ops
init:
  - git config --global core.autocrlf input

# Install stuff
install:

  - ps: Install-Product node 8 x64
  - choco install yarn --ignore-dependencies
  - git reset --hard HEAD
  - npm install -g xvfb-maybe

  # Sanity chceks
  - node --version
  - yarn --version

# Test and build
build_script:

  # Tests
  # Code linting and standards
  - yarn run lint

  # Unit tests
  - xvfb-maybe yarn run unit

  # End to end test
  - xvfb-maybe yarn run e2e

  # Build
  - yarn run build

test: off

environment:
  GH_TOKEN:
    secure: RE8jzDZrxCFiXFzJd1MGuUcfzBCgCf1Fql9XxH156pNgc4rWZn1PotGA9Po/iiDw
